/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       22
#define gattdb_firmware_revision_string       24
#define gattdb_system_id                      26
#define gattdb_automation_io                  27
#define gattdb_aio_digital_in                 29
#define gattdb_aio_num_of_digitals_in         32
#define gattdb_aio_digital_out                34
#define gattdb_aio_num_of_digitals_out        36
#define gattdb_battery_service                37
#define gattdb_batt_measurement               39
#define gattdb_power_source                   41
#define gattdb_power_source_type              43
#define gattdb_hall_state                     46
#define gattdb_hall_field_strength            49
#define gattdb_hall_control_point             52
#define gattdb_imu_acceleration               55
#define gattdb_imu_orientation                58
#define gattdb_imu_control_point              61
#define gattdb_environment_sensing            63
#define gattdb_es_ambient_light               65
#define gattdb_es_pressure                    67
#define gattdb_es_temperature                 69
#define gattdb_es_humidity                    71
#define gattdb_es_sound_level                 73
#define gattdb_ui_rgbleds                     76
#define gattdb_ui_rgbled_mask                 77
#define gattdb_ota                            78
#define gattdb_ota_control                    80


#endif // __GATT_DB_H
